language: enUS


#Defult setting
#languages
lang:
  enUS:
    message: 'Your language is English'
    pluginEnable: 'ArenaForFight is enable!'
    pluginDisable: 'ArenaForFight is disabled!'
    databaseConnect: 'Database is connected!'
    databaseDisconnect: 'Database not connected!'
    fightStartTitle: 'Fight Start!'
    fightStartSubtitle: 'Go punch his face!'
    askFight: 'asks to fight!'
    soloButton: 'Start SOLO Fight'
    soloButtonLore: 'Click to Start fight with your friend!'
    randomFightButton: 'Start random items Fight'
    randomFIghtButtonLore: 'Diamond or wood?'
    agreeFight: 'Agree fight'
    agreeFightLore: 'Agree to fight with you friend!'
    disagreeFight: 'Disagree fight'
    disagreeFightLore: 'Quit fight UI'
    win: 'You lose!'
    winSubline: 'Dont worry, win back next time!'
    lose: 'You WIN!'
    loseSubline: 'Keep Going!'
  cnZH:
    a: 'sdsd'
    message: 'this is Chinese version'
