language: enUS


#Defult setting
#languages
lang:
  enUS:
    fightStartTitle: 'Fight Start!'
    fightStartSubtitle: 'Go punch his face!'
    askFight: 'asks to fight!'
    soloButton: 'Start SOLO Fight'
    soloButtonLore: 'Click to Start fight with your friend!'
    randomFightButton: 'Start random items Fight'
    randomFIghtButtonLore: 'Diamond or wood?'
    agreeFight: 'Agree fight'
    agreeFightLore: 'Agree to fight with you friend!'
    disagreeFight: 'Disagree fight'
    disagreeFightLore: 'Quit fight UI'
    win: 'You win!'
    winSubline: 'keep going!'
    lose: 'You lose'
    loseSubline: 'Dont worry, win back next time!'
  cnZH:
    fightStartTitle: '战斗开始！'
    fightStartSubtitle: '去锤他的脸！'
    askFight: '询问你是否要战斗'
    soloButton: '开始1v1竞技'
    soloButtonLore: '点击和你的朋友们开始一场战斗'
    randomFightButton: '开始随机装备竞技'
    randomFightButtonLore: '钻石还是木头'
    agreeFight: '同意战斗'
    agreeFightLore: '同意和你的朋友战斗'
    disagreeFight: '拒绝战斗'
    disagreeFightLore: '退出竞技场UI'
    win: '你赢了！'
    winSubline: '继续保持'
    lose: '你输了:('
    loseSubline: '别担心，下次赢回来！'
pluginMessage:
  message: 'MicCheck micCheck'
  pluginEnable: 'The plugin start!'
  pluginDisable: 'The plugin stop'
  databaseConnect: 'The database connected!'
  databaseDisconncet: 'The database disconnected'
